### ISSUE TITLE
Hi, Triaton. This is Satan. Pls reply.

### ISSUE THREAD

**Issue by Rusleo-max** [triaton/satan#2]
Hi

**Comment by triaton** [comment]
I had to reimplement the resource viewer functionality because your github repository was not up-to-date.<be>
I implemented it in my own way and I could get the milestone released. You can check the repository yourself.

**Comment by Rusleo-max** [comment]
Great, thanks for your work.
Let me check my Github repository and update you if I have a question.

**Comment by Rusleo-max** [comment]
Hi, HR. I can not access to skype yet. Please keep working with Josh until I can access to skype.

**Comment by Rusleo-max** [comment]
Hi, Can you please send me the Webstorm crack file? Please upload it to this repository.
I am waiting for you here.
